# Generated by Django 3.1.1 on 2020-09-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='decription',
            new_name='description',
        ),
    ]
